# Config file for an example Majora's Mask: Recompiled mod.

# Fields that end up in the mod's manifest.
[manifest]

# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
# The name displayed in the mod management menu is separate from this so this doesn't need to be human readable.
id = "mm_recomp_song_utils"

# Version of this mod.
version = "1.0.2"

# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "Song Utilities"

# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description =  """
This mod introduces various improvements to song effects and playing the ocarina."""

# A short description that will show up in this mod's entry in the mod list. This should be human readable and kept short
# to prevent it from being cut off due to the limited space.
short_description = "Various ocarina-related improvements."

# Authors of this mod.
authors = [ "danielryb" ]

# ID of the target recomp game.
game_id = "mm"

# Minimum version of the target recomp (e.g. Zelda 64: Recompiled) that this mod can run on.
minimum_recomp_version = "1.2.0"

# Dependency mods. Each entry is the mod's ID and then an optional minimum version of the dependency mod.
dependencies = [
    "mm_recomp_message_hooks:1.0.0"
]

# Native libraries (e.g. DLLs) and the functions they export.
native_libraries = [
# Example native library:
#    { name = "my_native_library", funcs = ["my_native_library_function"] }
]

# Inputs to the mod tool.
[inputs]

# Input elf file to generate a mod from.
elf_path = "build/mod.elf"

# Output mod filename.
mod_filename = "mm_recomp_song_utils"

# Reference symbol files.
func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]

# Additional files to include in the mod.
additional_files = [
    "thumb.dds"
]

[[manifest.config_options]]
id = "reprise_skip_mode"
name = "Reprise Skip Mode"
description = """Allows the song reprise to be skipped.
"""
type = "Enum"
options = [
    "always",
    "button",
    "never"
]
default = "button"

[[manifest.config_options]]
id = "fix_note_positions"
name = "Fix Note Positions"
description = """Adjusts mismatched note positions on ocarina's staff.
"""
type = "Enum"
options = [
    "on",
    "off"
]
default = "on"

[[manifest.config_options]]
id = "disable_ocarina_input_limit"
name = "Disable ocarina's input limit"
description = """Disable the vanilla input limit of 1 ocarina note per 2 frames.
"""
type = "Enum"
options = [
    "on",
    "off"
]
default = "off"

[[manifest.config_options]]
id = "elegy_anywhere"
name = "Elegy of Emptiness Anywhere"
description = """Allows Elegy of Emptiness effect outside of Ikana Canyon.
"""
type = "Enum"
options = [
    "on",
    "off"
]
default = "on"

[[manifest.config_options]]
id = "stone_tower_block_placement_speed"
name = "Stone Tower Block Placement Speed"
description = "Determines the speed at which blocks in Stone Tower move towards their active position."
type = "Number"
min = 20
max = 200
step = 0.5
precision = 1
percent = false
default = 80

[[manifest.config_options]]
id = "stone_tower_block_return_speed"
name = "Stone Tower Block Return Speed"
description = "Determines the speed at which blocks in Stone Tower return to their default position."
type = "Number"
min = 20
max = 200
step = 0.5
precision = 1
percent = false
default = 100